from .users import user_router
from .products import product_router
from .orders import order_router
from .customers import customer_router
from .tags import tag_router
from .organizations import organization_router
from .billing import billing_router
from .fast_orders import fast_order_router
from .expenses import expenses_router
from .invites import invite_router
from .payments import payment_router
from .organization_plans import organization_plan_router
from .plans import plan_router
from .plan_features import plan_feature_router
from .mercado_pago import mercado_pago_router
from .subscriptions import subscription_router
from .coupons import coupon_router
from .marketing_emails import marketing_email_router
from .calendar import calendar_router
from .terms_of_use import term_of_use_router
from .files import file_router
from .sections import section_router
from .section_offers import section_offer_router
from .menus import menu_router
from .offers import offer_router
from .home import home_router
from .pre_orders import pre_order_router
from .messages import message_router
