from .users import user_router
from .products import product_router
from .orders import order_router
from .customers import customer_router
from .tags import tag_router
from .organizations import organization_router
from .billing import billing_router
from .fast_orders import fast_order_router
from .expenses import expenses_router
from .invites import invite_router
from .payments import payment_router
from .images import images_router
from .organization_plans import organization_plan_router
from .plans import plan_router
from .plan_features import plan_feature_router
from .mercado_pago import mercado_pago_router
from .subscriptions import subscription_router
from .coupons import coupon_router
from .marketing_emails import marketing_email_router
