from .users import user_router
from .products import product_router
from .authetication import authentication_router
from .orders import order_router
from .customers import customer_router
from .tags import tag_router
from .organizations import organization_router
from .financial import financial_router
from .fast_orders import fast_order_router
from .expenses import expenses_router
