version: "3.8"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - network

  api:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - network

networks:
  network:
    external: false
