# fly.toml app configuration file generated for sweetshop on 2024-12-04T01:06:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sweetshop'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  domains = ["api.pedidoz.online"]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 0.5
